### ISSUE TITLE
predict.Cartogram() produces wrong results

### ISSUE THREAD

**Issue by theGreatWhiteShark** [omegahat/Rcartogram#4]
When using the C-based method predict.Cartogram with two coordinates it returns just the result of the second coordinate two times. The transformed first coordinate seems to get overwritten in the C call *R_predict*.

The commented R-based predict.Cartogram methods, on the other hand, works just fine.

**Comment by duncantl** [comment]
Thanks. Do you have a short example illustrating this?

**Comment by duncantl** [comment]
If you have a chance, check the updated version on github.  Thanks.

**Comment by theGreatWhiteShark** [comment]
The error occurred already in the default example of in the *cartogram()* help. 
But with the updated version everything works just fine. Thanks a lot for the quick response/fix!

One more thing: the example of *cartogram()* features the line
> filename = system.file("data", "uspop.tab.gz", package = "Rcartogram")

But since the featured file "uspop.tab" is not compressed the example fails.

**Comment by duncantl** [comment]
Thanks. New update pushed.

**Comment by theGreatWhiteShark** [comment]
Perfect
